export interface HandVector {
    rightThumbTipToFirstJoint: number[] | null;
    rightThumbFirstJointToSecondJoint: number[] | null;
    rightIndexFingerTipToFirstJoint: number[] | null;
    rightIndexFingerFirstJointToSecondJoint: number[] | null;
    rightMiddleFingerTipToFirstJoint: number[] | null;
    rightMiddleFingerFirstJointToSecondJoint: number[] | null;
    rightRingFingerTipToFirstJoint: number[] | null;
    rightRingFingerFirstJointToSecondJoint: number[] | null;
    rightPinkyFingerTipToFirstJoint: number[] | null;
    rightPinkyFingerFirstJointToSecondJoint: number[] | null;
    leftThumbTipToFirstJoint: number[] | null;
    leftThumbFirstJointToSecondJoint: number[] | null;
    leftIndexFingerTipToFirstJoint: number[] | null;
    leftIndexFingerFirstJointToSecondJoint: number[] | null;
    leftMiddleFingerTipToFirstJoint: number[] | null;
    leftMiddleFingerFirstJointToSecondJoint: number[] | null;
    leftRingFingerTipToFirstJoint: number[] | null;
    leftRingFingerFirstJointToSecondJoint: number[] | null;
    leftPinkyFingerTipToFirstJoint: number[] | null;
    leftPinkyFingerFirstJointToSecondJoint: number[] | null;
}
