export interface HandVector {
  // 右手 - 親指
  rightThumbTipToFirstJoint: number[] | null;
  rightThumbFirstJointToSecondJoint: number[] | null;
  // 右手 - 人差し指
  rightIndexFingerTipToFirstJoint: number[] | null;
  rightIndexFingerFirstJointToSecondJoint: number[] | null;
  // 右手 - 中指
  rightMiddleFingerTipToFirstJoint: number[] | null;
  rightMiddleFingerFirstJointToSecondJoint: number[] | null;
  // 右手 - 薬指
  rightRingFingerTipToFirstJoint: number[] | null;
  rightRingFingerFirstJointToSecondJoint: number[] | null;
  // 右手 - 小指
  rightPinkyFingerTipToFirstJoint: number[] | null;
  rightPinkyFingerFirstJointToSecondJoint: number[] | null;
  // 左手 - 親指
  leftThumbTipToFirstJoint: number[] | null;
  leftThumbFirstJointToSecondJoint: number[] | null;
  // 左手 - 人差し指
  leftIndexFingerTipToFirstJoint: number[] | null;
  leftIndexFingerFirstJointToSecondJoint: number[] | null;
  // 左手 - 中指
  leftMiddleFingerTipToFirstJoint: number[] | null;
  leftMiddleFingerFirstJointToSecondJoint: number[] | null;
  // 左手 - 薬指
  leftRingFingerTipToFirstJoint: number[] | null;
  leftRingFingerFirstJointToSecondJoint: number[] | null;
  // 左手 - 小指
  leftPinkyFingerTipToFirstJoint: number[] | null;
  leftPinkyFingerFirstJointToSecondJoint: number[] | null;
}
